from __future__ import annotations

import subprocess
import sys
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


COMMANDS = {
    "source-check": [
        ["scripts/harness/verify_research_source_map.py"],
    ],
    "skill-check": [
        ["scripts/harness/verify_skill_frontmatter.py"],
        ["scripts/harness/verify_skill_constraints.py"],
    ],
    "math-check": [
        ["scripts/harness/verify_no_pbft_residue.py"],
        ["scripts/harness/verify_no_sampling_avalanche.py"],
        ["scripts/harness/verify_no_binomial_enumeration.py"],
    ],
    "model-check": [
        ["-m", "unittest", "discover", "-s", "tests/models"],
    ],
    "topology-check": [
        ["-m", "unittest", "discover", "-s", "tests/topology"],
        ["scripts/harness/verify_no_soft_hard_gap.py"],
    ],
    "loss-check": [
        ["-m", "unittest", "discover", "-s", "tests/loss"],
        ["scripts/harness/verify_no_link_reliability_loss.py"],
    ],
    "training-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training"],
        ["scripts/analysis/run_training_smoke.py", "--config", "configs/training_smoke.yaml", "--smoke"],
    ],
    "training-stability-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_training_stability_smoke.py"],
        ["scripts/analysis/run_training_stability_smoke.py", "--tier", "smoke"],
    ],
    "training-stability-short-check": [
        ["scripts/analysis/run_training_stability_smoke.py", "--tier", "short"],
    ],
    "training-stability-short-20-check": [
        ["scripts/analysis/run_training_stability_smoke.py", "--tier", "short", "--max-steps-override", "20"],
    ],
    "training-stability-analysis-check": [
        ["scripts/analysis/run_training_stability_smoke.py", "--tier", "analysis"],
    ],
    "minimal-experiment-micro-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_minimal_experiment.py"],
        ["scripts/analysis/run_minimal_experiment.py", "--tier", "micro"],
    ],
    "minimal-experiment-smoke-check": [
        ["scripts/analysis/run_minimal_experiment.py", "--tier", "smoke"],
    ],
    "controlled-ablation-micro-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_controlled_ablation.py"],
        ["scripts/analysis/run_controlled_ablation.py", "--tier", "micro"],
    ],
    "controlled-ablation-smoke-check": [
        ["scripts/analysis/run_controlled_ablation.py", "--tier", "smoke"],
    ],
    "controlled-ablation-short-check": [
        ["scripts/analysis/run_controlled_ablation.py", "--tier", "short"],
    ],
    "controlled-ablation-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_controlled_ablation_report.py"],
    ],
    "selected-ablation-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_ablation_evidence.py"],
        ["scripts/analysis/run_selected_ablation_evidence.py", "--preset", "smoke"],
    ],
    "selected-ablation-short-check": [
        ["scripts/analysis/run_selected_ablation_evidence.py", "--preset", "short"],
    ],
    "calibrated-structural-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_calibrated_structural_followup.py"],
        ["scripts/analysis/run_calibrated_structural_followup.py", "--tier", "smoke"],
    ],
    "calibrated-structural-short-check": [
        ["scripts/analysis/run_calibrated_structural_followup.py", "--tier", "short"],
    ],
    "selected-training-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_training_smoke.py"],
    ],
    "selected-training-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_training_report.py"],
    ],
    "selected-training-multiseed-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_training_multiseed.py"],
    ],
    "selected-short-training-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_short_training.py"],
    ],
    "selected-short-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_selected_short_report.py"],
    ],
    "controlled-selected-short-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_controlled_selected_short.py"],
    ],
    "support-matched-audit-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_support_matched_audit.py"],
    ],
    "fixed-support-audit-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_fixed_support_audit.py"],
    ],
    "structural-redesign-review-check": [
        ["-m", "unittest", "discover", "-s", "tests/models", "-p", "test_structural_redesign_review.py"],
        ["scripts/analysis/report_structural_redesign_review.py", "--no-write"],
    ],
    "baseline-consolidation-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_baseline_consolidation.py"],
        ["scripts/analysis/run_baseline_consolidation.py", "--no-write"],
    ],
    "pure-edge-baseline-stability-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_baseline_stability.py"],
    ],
    "pure-edge-baseline-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_baseline_report.py"],
        [
            "scripts/analysis/report_pure_edge_baseline_stability.py",
            "--json-in",
            ".agent/tmp/pure_edge_baseline_stability.json",
            "--no-write",
        ],
    ],
    "pure-edge-selected-short-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_selected_short.py"],
    ],
    "pure-edge-selected-short-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_selected_short_report.py"],
        [
            "scripts/analysis/report_pure_edge_selected_short.py",
            "--json-in",
            ".agent/tmp/pure_edge_selected_short.json",
            "--no-write",
        ],
    ],
    "pure-edge-followup-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_followup.py"],
    ],
    "pure-edge-reference-package-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_reference_package.py"],
        ["scripts/analysis/build_pure_edge_reference_package.py", "--no-write"],
    ],
    "pure-edge-baseline-extension-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_baseline_extension.py"],
    ],
    "pure-edge-baseline-extension-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_baseline_extension_report.py"],
        [
            "scripts/analysis/report_pure_edge_baseline_extension.py",
            "--json-in",
            ".agent/tmp/pure_edge_baseline_extension.json",
            "--no-write",
        ],
    ],
    "pure-edge-benchmark-package-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_pure_edge_benchmark_package.py"],
        ["scripts/analysis/build_pure_edge_benchmark_package.py", "--no-write"],
    ],
    "training-v0-config-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_training_v0_config.py"],
        ["scripts/analysis/validate_training_v0_config.py", "--no-write"],
    ],
    "formal-training-v0-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_smoke.py"],
        ["scripts/analysis/run_formal_training_v0_smoke.py", "--max-steps-override", "1", "--no-write"],
    ],
    "formal-training-v0-baseline-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_baseline.py"],
        ["scripts/analysis/run_formal_training_v0_baseline.py", "--max-steps-override", "2", "--no-write"],
    ],
    "formal-training-v0-baseline-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_baseline_report.py"],
        [
            "scripts/analysis/report_formal_training_v0_baseline.py",
            "--json-in",
            ".agent/tmp/formal_training_v0_baseline.json",
            "--no-write",
        ],
    ],
    "formal-training-v0-full-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_full.py"],
        ["scripts/analysis/run_formal_training_v0_full.py", "--max-steps-override", "2", "--no-write"],
    ],
    "formal-training-v0-full-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_full_report.py"],
        [
            "scripts/analysis/report_formal_training_v0_full.py",
            "--json-in",
            ".agent/tmp/formal_training_v0_full.json",
            "--no-write",
        ],
    ],
    "formal-training-v0-small-realistic-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_small_realistic.py"],
        ["scripts/analysis/run_formal_training_v0_small_realistic.py", "--max-steps-override", "2", "--no-write"],
    ],
    "formal-training-v0-small-realistic-report-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_small_realistic_report.py"],
        [
            "scripts/analysis/report_formal_training_v0_small_realistic.py",
            "--json-in",
            ".agent/tmp/formal_training_v0_small_realistic.json",
            "--no-write",
        ],
    ],
    "formal-training-v0-package-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_baseline_package.py"],
        ["scripts/analysis/build_formal_training_v0_baseline_package.py", "--no-write"],
    ],
    "controlled-v0-baseline-extension-check": [
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_controlled_v0_baseline_extension.py"],
        [
            "scripts/analysis/run_controlled_v0_baseline_extension.py",
            "--node-count",
            "100",
            "--profiles",
            "toy",
            "--seeds",
            "7",
            "--support-policies",
            "all,topk,all_to_topk",
            "--max-steps-override",
            "1",
            "--no-write",
        ],
    ],
    "controlled-v0-baseline-extension-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_controlled_v0_baseline_extension_report.py",
        ],
        [
            "scripts/analysis/report_controlled_v0_baseline_extension.py",
            "--json-in",
            ".agent/tmp/controlled_v0_baseline_extension.json",
            "--no-write",
        ],
    ],
    "formal-training-v0-package-v1-1-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_formal_training_v0_baseline_package_v1_1.py",
        ],
        ["scripts/analysis/build_formal_training_v0_baseline_package_v1_1.py", "--no-write"],
    ],
    "scale-profile-extension-plan-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_profile_extension_plan.py",
        ],
        [
            "scripts/analysis/report_scale_profile_extension_plan.py",
            "--json-in",
            ".agent/tmp/formal_training_v0_baseline_package_v1_1.json",
            "--no-write",
        ],
    ],
    "topk-flatness-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_topk_flatness_diagnostic.py",
        ],
        [
            "scripts/analysis/run_topk_flatness_diagnostic.py",
            "--max-steps-override",
            "1",
            "--no-write",
        ],
    ],
    "runtime-memory-scaling-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling.py",
        ],
        ["scripts/analysis/run_runtime_memory_scaling.py", "--no-write"],
    ],
    "node-count-2000-topk-smoke-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_2000_topk_smoke.py",
        ],
        ["scripts/analysis/run_node_count_2000_topk_smoke.py", "--no-write"],
    ],
    "node-count-5000-topk-smoke-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_5000_topk_smoke.py",
        ],
        [
            "scripts/analysis/run_node_count_5000_topk_smoke.py",
            "--node-count",
            "500",
            "--force",
            "--no-write",
        ],
    ],
    "node-count-10000-topk-forward-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_10000_topk_forward_smoke.py",
        ],
        [
            "scripts/analysis/run_node_count_10000_topk_forward_smoke.py",
            "--node-count",
            "500",
            "--force",
            "--no-write",
        ],
    ],
    "node-count-10000-topk-backward-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_10000_topk_backward_smoke.py",
        ],
        [
            "scripts/analysis/run_node_count_10000_topk_backward_smoke.py",
            "--node-count",
            "500",
            "--force",
            "--no-write",
        ],
    ],
    "node-count-10000-topk-backward-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_10000_topk_backward_report.py",
        ],
        [
            "scripts/analysis/report_node_count_10000_topk_backward.py",
            "--json-in",
            ".agent/tmp/node_count_10000_topk_backward_smoke.json",
            "--no-write",
        ],
    ],
    "gradient-step-size-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_gradient_step_size_diagnostic.py",
        ],
        [
            "scripts/analysis/run_gradient_step_size_diagnostic.py",
            "--node-count",
            "500",
            "--learning-rates",
            "1e-4,1e-3,1e-2",
            "--force",
            "--no-write",
        ],
    ],
    "gradient-source-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_gradient_source_diagnostic.py",
        ],
        [
            "scripts/analysis/run_gradient_source_diagnostic.py",
            "--node-count",
            "500",
            "--loss-scales",
            "1,10",
            "--learning-rates",
            "1e-2,1e-1",
            "--force",
            "--no-write",
        ],
    ],
    "loss-scale-calibrated-backward-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_loss_scale_calibrated_backward_smoke.py",
        ],
        [
            "scripts/analysis/run_loss_scale_calibrated_backward_smoke.py",
            "--node-count",
            "500",
            "--loss-scale",
            "1000",
            "--learning-rate",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "tenk-few-step-training-smoke-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_tenk_few_step_training_smoke.py",
        ],
        [
            "scripts/analysis/run_tenk_few_step_training_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "metric-flatness-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_metric_flatness_diagnostic.py",
        ],
        [
            "scripts/analysis/run_metric_flatness_diagnostic.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--perturb-edge-score-scales",
            "1e-5,1e-3",
            "--edge-score-only-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "topk-support-sensitivity-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_topk_support_sensitivity_probe.py",
        ],
        [
            "scripts/analysis/run_topk_support_sensitivity_probe.py",
            "--node-count",
            "500",
            "--perturb-scales",
            "1e-6,1e-4,1e-2",
            "--score-scales",
            "0.1,1,10",
            "--softmax-temperatures",
            "0.5,1,2",
            "--force",
            "--no-write",
        ],
    ],
    "score-scale-calibration-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scale_calibration.py",
        ],
        [
            "scripts/analysis/run_score_scale_calibration.py",
            "--node-count",
            "500",
            "--score-scales",
            "1,3,10",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "score-scaled-tenk-few-step-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scaled_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_score_scaled_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "3",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "score-scaled-tenk-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scaled_tenk_report.py",
        ],
        [
            "scripts/analysis/report_score_scaled_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/score_scaled_tenk_few_step_smoke.json",
            "--no-write",
        ],
    ],
    "score-temperature-grid-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_temperature_grid_probe.py",
        ],
        [
            "scripts/analysis/run_score_temperature_grid_probe.py",
            "--node-count",
            "500",
            "--score-scales",
            "3,10",
            "--temperatures",
            "1,2",
            "--probe-steps",
            "1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "row-softmax-temperature-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_row_softmax_temperature_design.py",
        ],
        [
            "scripts/analysis/report_row_softmax_temperature_design.py",
            "--json-in",
            ".agent/tmp/score_temperature_grid_probe.json",
            "--no-write",
        ],
    ],
    "row-softmax-temperature-constructor-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_row_softmax_temperature_constructor.py",
        ],
        [
            "scripts/analysis/report_row_softmax_temperature_constructor.py",
            "--force",
            "--no-write",
        ],
    ],
    "formal-temperature-grid-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_formal_temperature_grid_probe.py",
        ],
        [
            "scripts/analysis/run_formal_temperature_grid_probe.py",
            "--node-count",
            "500",
            "--score-scales",
            "3,10",
            "--temperatures",
            "1,0.5",
            "--probe-steps",
            "1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "temperature-aware-tenk-few-step-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "temperature-aware-tenk-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_tenk_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/temperature_aware_tenk_few_step_smoke.json",
            "--no-write",
        ],
    ],
    "temperature-aware-longer-tenk-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_longer_tenk_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_longer_tenk_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "temperature-aware-longer-tenk-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_longer_tenk_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_longer_tenk.py",
            "--json-in",
            ".agent/tmp/temperature_aware_longer_tenk_smoke.json",
            "--no-write",
        ],
    ],
    "temperature-aware-30step-tenk-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_30step_tenk_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_30step_tenk_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "temperature-aware-30step-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_30step_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_30step_tenk.py",
            "--json-in",
            ".agent/tmp/temperature_aware_30step_tenk_smoke.json",
            "--no-write",
        ],
    ],
    "all-mode-warm-start-10k-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_all_mode_warm_start_10k_probe.py",
        ],
        [
            "scripts/analysis/run_all_mode_warm_start_10k_probe.py",
            "--node-count",
            "1000",
            "--max-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "all-mode-warm-start-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_all_mode_warm_start_report.py",
        ],
        [
            "scripts/analysis/report_all_mode_warm_start_10k.py",
            "--json-in",
            ".agent/tmp/all_mode_warm_start_10k_probe.json",
            "--no-write",
        ],
    ],
    "convergence-root-cause-audit-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_convergence_root_cause_audit.py",
        ],
        [
            "scripts/analysis/run_convergence_root_cause_audit.py",
            "--node-count",
            "500",
            "--force",
            "--no-write",
        ],
    ],
    "scorer-parameterization-redesign-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_scorer_parameterization_redesign.py",
        ],
        [
            "scripts/analysis/report_scorer_parameterization_redesign.py",
            "--json-in",
            ".agent/tmp/convergence_root_cause_audit.json",
            "--no-write",
        ],
    ],
    "scorer-dynamic-range-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_scorer_dynamic_range_diagnostic.py",
        ],
        [
            "scripts/analysis/run_scorer_dynamic_range_diagnostic.py",
            "--node-count",
            "500",
            "--score-scales",
            "1,10,30",
            "--force",
            "--no-write",
        ],
    ],
    "score-output-gain-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_score_output_gain.py",
        ],
    ],
    "score-output-gain-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_output_gain_probe.py",
        ],
        [
            "scripts/analysis/run_score_output_gain_probe.py",
            "--node-count",
            "500",
            "--score-output-gains",
            "1,10,30",
            "--probe-steps",
            "1",
            "--force",
            "--no-write",
        ],
    ],
    "score-gain-tenk-few-step-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_gain_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_score_gain_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--compare-gains",
            "10,30",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "score-gain-tenk-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_gain_tenk_report.py",
        ],
        [
            "scripts/analysis/report_score_gain_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/score_gain_tenk_few_step_smoke.json",
            "--no-write",
        ],
    ],
    "combined-gain-temperature-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_combined_gain_temperature_probe.py",
        ],
        [
            "scripts/analysis/run_combined_gain_temperature_probe.py",
            "--node-count",
            "500",
            "--probe-steps",
            "2",
            "--score-output-gains",
            "10,30",
            "--temperatures",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "edge-score-teacher-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_teacher_probe.py",
        ],
        [
            "scripts/analysis/run_edge_score_teacher_probe.py",
            "--node-count",
            "500",
            "--teacher-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "edge-score-teacher-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_teacher_report.py",
        ],
        [
            "scripts/analysis/report_edge_score_teacher_probe.py",
            "--json-in",
            ".agent/tmp/edge_score_teacher_probe.json",
            "--no-write",
        ],
    ],
    "teacher-guided-scorer-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_guided_scorer_design.py",
        ],
        [
            "scripts/analysis/report_teacher_guided_scorer_design.py",
            "--json-in",
            ".agent/tmp/edge_score_teacher_interpretation.json",
            "--no-write",
        ],
    ],
    "edge-score-delta-distillation-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_delta_distillation.py",
        ],
        [
            "scripts/analysis/run_edge_score_delta_distillation.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--teacher-weights",
            "0.01,0.1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "edge-score-delta-distillation-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_delta_distillation_report.py",
        ],
        [
            "scripts/analysis/report_edge_score_delta_distillation.py",
            "--json-in",
            ".agent/tmp/edge_score_delta_distillation.json",
            "--no-write",
        ],
    ],
    "teacher-loss-scale-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_loss_scale_probe.py",
        ],
        [
            "scripts/analysis/run_teacher_loss_scale_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--teacher-weights",
            "1,1e3",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "teacher-loss-scale-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_loss_scale_report.py",
        ],
        [
            "scripts/analysis/report_teacher_loss_scale_probe.py",
            "--json-in",
            ".agent/tmp/teacher_loss_scale_probe.json",
            "--no-write",
        ],
    ],
    "directional-teacher-alignment-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_directional_teacher_alignment_probe.py",
        ],
        [
            "scripts/analysis/run_directional_teacher_alignment_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--alignment-modes",
            "cosine_delta_alignment",
            "--teacher-weights",
            "0.1,1.0",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "directional-teacher-alignment-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_directional_teacher_alignment_interpretation.py",
        ],
        [
            "scripts/analysis/report_directional_teacher_alignment.py",
            "--json-in",
            ".agent/tmp/directional_teacher_alignment_probe.json",
            "--no-write",
        ],
    ],
    "score-head-teacher-update-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_head_teacher_update_probe.py",
        ],
        [
            "scripts/analysis/run_score_head_only_teacher_update_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--alignment-modes",
            "sign_alignment",
            "--teacher-weights",
            "0.01,0.1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
    ],
    "support-smoothing-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_design.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_design.py",
            "--json-in",
            ".agent/tmp/score_head_only_teacher_update_probe.json",
            "--no-write",
        ],
    ],
    "support-smoothing-constructor-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_support_smoothing_constructor.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_constructor.py",
            "--readiness-artifact",
            ".agent/tmp/support_smoothing_design.json",
            "--no-write",
        ],
    ],
    "support-smoothing-10k-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_10k_smoke.py",
        ],
        [
            "scripts/analysis/run_support_smoothing_10k_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--no-write",
        ],
    ],
    "loss-evaluator-sensitivity-review-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_loss_evaluator_sensitivity_review.py",
        ],
        [
            "scripts/analysis/report_loss_evaluator_sensitivity_review.py",
            "--json-in",
            ".agent/tmp/support_smoothing_10k_smoke.json",
            "--no-write",
        ],
    ],
    "human-review-gate-package-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_human_review_gate_package.py",
        ],
        [
            "scripts/analysis/report_human_review_gate_package.py",
            "--json-in",
            ".agent/tmp/loss_evaluator_sensitivity_review.json",
            "--no-write",
        ],
    ],
    "support-smoothing-stabilization-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_stabilization_design.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_stabilization_design.py",
            "--no-write",
        ],
    ],
    "conservative-support-smoothing-sweep-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_conservative_support_smoothing_sweep.py",
        ],
        [
            "scripts/analysis/run_conservative_support_smoothing_sweep.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--no-write",
        ],
    ],
    "full-10k-support-smoothing-smoke-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_full_10k_support_smoothing_smoke.py",
        ],
        [
            "scripts/analysis/run_full_10k_support_smoothing_smoke.py",
            "--max-steps",
            "1",
            "--no-write",
        ],
    ],
    "support-smoothing-scale-transfer-audit-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_scale_transfer_audit.py",
        ],
        [
            "scripts/analysis/run_support_smoothing_scale_transfer_audit.py",
            "--node-counts",
            "100,500",
            "--steps",
            "1",
            "--no-write",
        ],
    ],
    "scale-aware-update-normalization-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_aware_update_normalization_design.py",
        ],
        ["scripts/analysis/report_scale_aware_update_normalization_design.py", "--no-write"],
    ],
    "scale-aware-update-normalization-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_aware_update_normalization_probe.py",
        ],
        [
            "scripts/analysis/run_scale_aware_update_normalization_probe.py",
            "--node-counts",
            "500,2000",
            "--steps",
            "1",
            "--normalization-basis",
            "node_count",
            "--normalization-exponents",
            "0.5",
            "--normalization-max-multipliers",
            "10",
            "--force",
            "--no-write",
        ],
    ],
    "scale-law-root-cause-audit-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_law_root_cause_audit.py",
        ],
        ["scripts/analysis/report_scale_law_root_cause_audit.py", "--no-write"],
    ],
    "scale-law-remediation-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_law_remediation_design.py",
        ],
        ["scripts/analysis/report_scale_law_remediation_design.py", "--no-write"],
    ],
    "scale-invariant-loss-update-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_invariant_loss_update_design.py",
        ],
        ["scripts/analysis/report_scale_invariant_loss_update_design.py", "--no-write"],
    ],
    "scale-invariant-design-review-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_invariant_design_review.py",
        ],
        ["scripts/analysis/report_scale_invariant_design_review.py", "--no-write"],
    ],
    "topology-smoothing-mass-query-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_topology_smoothing_mass_query_diagnostic.py",
        ],
        [
            "scripts/analysis/run_topology_smoothing_mass_query_diagnostic.py",
            "--node-counts",
            "100",
            "--steps",
            "1",
            "--force",
            "--no-write",
        ],
    ],
    "query-support-sensitivity-counterfactual-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_query_support_sensitivity_counterfactual_probe.py",
        ],
        [
            "scripts/analysis/run_query_support_sensitivity_counterfactual_probe.py",
            "--node-counts",
            "100",
            "--perturbation-scales",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "realistic-density-perturbation-capacity-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_realistic_density_perturbation_capacity_diagnostic.py",
        ],
        [
            "scripts/analysis/run_realistic_density_perturbation_capacity_diagnostic.py",
            "--node-counts",
            "100",
            "--profiles",
            "toy,small_realistic",
            "--perturbation-scales",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "production-density-profile-probe-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_production_density_profile_probe.py",
        ],
        [
            "scripts/analysis/run_production_density_profile_probe.py",
            "--node-counts",
            "100,500",
            "--profiles",
            "toy,small_realistic,production_like_density_v0",
            "--force",
            "--no-write",
        ],
    ],
    "production-profile-perturbation-capacity-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_production_profile_perturbation_capacity_probe.py",
        ],
        [
            "scripts/analysis/run_production_profile_perturbation_capacity_probe.py",
            "--node-counts",
            "100",
            "--perturbation-scales",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "production-profile-training-signal-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_production_profile_training_signal_diagnostic.py",
        ],
        [
            "scripts/analysis/run_production_profile_training_signal_diagnostic.py",
            "--node-counts",
            "100",
            "--edge-score-perturbation-scales",
            "1e-4",
            "--projected-learning-rates",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "loss-to-score-gradient-alignment-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_loss_to_score_gradient_alignment_diagnostic.py",
        ],
        [
            "scripts/analysis/run_loss_to_score_gradient_alignment_diagnostic.py",
            "--node-counts",
            "100",
            "--perturbation-scales",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "constructor-jacobian-alignment-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_constructor_jacobian_alignment_diagnostic.py",
        ],
        [
            "scripts/analysis/run_constructor_jacobian_alignment_diagnostic.py",
            "--node-counts",
            "100",
            "--focus-node-count",
            "100",
            "--perturbation-scales",
            "1e-4",
            "--force",
            "--no-write",
        ],
    ],
    "evaluator-bottleneck-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/evaluation",
            "-p",
            "test_evaluator_profile.py",
        ],
        [
            "scripts/analysis/profile_v2x_evaluator.py",
            "--node-counts",
            "500,1000",
            "--force",
            "--no-write",
        ],
    ],
    "query-support-optimization-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/consensus",
            "-p",
            "test_query_support_optimization_design.py",
        ],
        [
            "scripts/analysis/report_query_support_optimization_design.py",
            "--json-in",
            ".agent/tmp/evaluator_bottleneck_diagnostic.json",
            "--no-write",
        ],
    ],
    "query-support-fast-path-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/consensus",
            "-p",
            "test_topology_query_support_fast_path.py",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/evaluation",
            "-p",
            "test_v2x_consensus_bridge_query_support_backend.py",
        ],
        [
            "scripts/analysis/profile_v2x_evaluator.py",
            "--node-counts",
            "500",
            "--force",
            "--query-support-backend",
            "both",
            "--diagnostics-mode",
            "full",
            "--no-write",
        ],
    ],
    "runtime-memory-scaling-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling_report.py",
        ],
        ["scripts/analysis/report_runtime_memory_scaling.py", "--no-write"],
    ],
    "runtime-memory-scaling-v1-1-report-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling_v1_1_report.py",
        ],
        ["scripts/analysis/report_runtime_memory_scaling_v1_1.py", "--no-write"],
    ],
    "constructor-bottleneck-diagnostic-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_constructor_profile.py",
        ],
        ["scripts/analysis/profile_topology_constructor.py", "--node-counts", "100,500", "--no-write"],
    ],
    "constructor-optimization-design-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_constructor_optimization_design.py",
        ],
        [
            "scripts/analysis/report_constructor_optimization_design.py",
            "--json-in",
            ".agent/tmp/constructor_bottleneck_diagnostic.json",
            "--no-write",
        ],
    ],
    "topology-constructor-fast-path-check": [
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_topology_construction_fast_path.py",
        ],
        [
            "scripts/analysis/profile_topology_constructor.py",
            "--node-counts",
            "64",
            "--topk-backend",
            "both",
            "--force",
            "--no-write",
        ],
    ],
    "structural-signal-audit-check": [
        ["-m", "unittest", "discover", "-s", "tests/models", "-p", "test_structural_signal_audit.py"],
        ["scripts/analysis/audit_structural_heads.py", "--smoke"],
    ],
    "structural-weight-sweep-check": [
        ["-m", "unittest", "discover", "-s", "tests/models", "-p", "test_structural_weight_sweep.py"],
        ["scripts/analysis/sweep_structural_weights.py", "--smoke"],
    ],
    "training-smoke-curriculum-check": [
        ["scripts/analysis/run_training_smoke.py", "--config", "configs/training_smoke.yaml", "--smoke", "--curriculum"],
    ],
    "training-smoke-small-realistic-check": [
        [
            "scripts/analysis/run_training_smoke.py",
            "--config",
            "configs/training_smoke.yaml",
            "--smoke",
            "--avalanche-profile",
            "small_realistic",
        ],
    ],
    "scale-training-fast-check": [
        ["-m", "unittest", "discover", "-s", "tests/scale"],
        ["scripts/analysis/run_scale_training_smoke.py", "--tier", "fast"],
    ],
    "scale-training-smoke-check": [
        ["-m", "unittest", "discover", "-s", "tests/scale"],
        ["scripts/analysis/run_scale_training_smoke.py", "--tier", "fast"],
    ],
    "scale-training-medium-check": [
        ["scripts/analysis/run_scale_training_smoke.py", "--tier", "medium"],
    ],
    "scale-training-large-check": [
        ["scripts/analysis/run_scale_training_smoke.py", "--tier", "large"],
    ],
    "runtime-env-check": [
        ["scripts/analysis/check_runtime_environment.py"],
    ],
    "env-feasibility-check": [
        ["-m", "unittest", "discover", "-s", "tests/environment"],
        ["scripts/harness/verify_sparse_complexity.py"],
        [
            "scripts/calibrate_environment.py",
            "--config",
            "configs/physical_search.yaml",
            "--smoke",
            "--json-out",
            ".agent/tmp/environment_feasibility.json",
            "--md-out",
            ".agent/tmp/environment_feasibility.md",
            "--write-medium-config",
            ".agent/tmp/environment_medium.yaml",
        ],
    ],
    "env-feasibility-report": [
        [
            "scripts/calibrate_environment.py",
            "--config",
            "configs/physical_search.yaml",
            "--smoke",
            "--json-out",
            "reports/environment_feasibility.json",
            "--md-out",
            "reports/environment_feasibility.md",
            "--write-medium-config",
            "configs/environment_medium.yaml",
        ],
    ],
    "evaluation-check": [
        ["-m", "unittest", "discover", "-s", "tests/evaluation"],
        ["scripts/harness/verify_no_pbft_residue.py"],
        ["scripts/harness/verify_no_sampling_avalanche.py"],
        ["scripts/harness/verify_no_binomial_enumeration.py"],
        ["scripts/harness/verify_no_link_reliability_loss.py"],
        ["scripts/harness/verify_sparse_complexity.py"],
    ],
    "evaluation-sweep-check": [
        ["scripts/analysis/sweep_v2x_consensus_bridge.py", "--smoke", "--profile", "small-realistic"],
    ],
    "evaluation-scale-check": [
        ["scripts/analysis/evaluation_scale_smoke.py"],
        ["scripts/harness/verify_sparse_complexity.py"],
    ],
    "integration-check": [
        ["-m", "unittest", "discover", "-s", "tests/integration"],
    ],
    "scale-smoke": [
        ["scripts/harness/verify_sparse_complexity.py"],
    ],
    "harness-check": [
        ["-m", "unittest", "discover", "-s", "tests/models"],
        ["-m", "unittest", "discover", "-s", "tests/evaluation"],
        ["-m", "unittest", "discover", "-s", "tests/integration"],
        ["-m", "unittest", "discover", "-s", "tests/topology"],
        ["-m", "unittest", "discover", "-s", "tests/training"],
        ["scripts/analysis/run_training_smoke.py", "--config", "configs/training_smoke.yaml", "--smoke"],
        ["scripts/analysis/run_training_stability_smoke.py", "--tier", "smoke"],
        ["scripts/analysis/run_controlled_ablation.py", "--tier", "micro"],
        ["scripts/analysis/run_selected_ablation_evidence.py", "--preset", "smoke"],
        ["scripts/analysis/run_calibrated_structural_followup.py", "--tier", "smoke"],
        ["scripts/analysis/validate_training_v0_config.py", "--no-write"],
        ["-m", "unittest", "discover", "-s", "tests/training", "-p", "test_formal_training_v0_baseline_package.py"],
        ["scripts/analysis/build_formal_training_v0_baseline_package.py", "--no-write"],
        [
            "scripts/analysis/report_controlled_v0_baseline_extension.py",
            "--json-in",
            ".agent/tmp/controlled_v0_baseline_extension.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_formal_training_v0_baseline_package_v1_1.py",
        ],
        ["scripts/analysis/build_formal_training_v0_baseline_package_v1_1.py", "--no-write"],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_scale_profile_extension_plan.py",
        ],
        [
            "scripts/analysis/report_scale_profile_extension_plan.py",
            "--json-in",
            ".agent/tmp/formal_training_v0_baseline_package_v1_1.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_topk_flatness_diagnostic.py",
        ],
        [
            "scripts/analysis/run_topk_flatness_diagnostic.py",
            "--max-steps-override",
            "1",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling.py",
        ],
        ["scripts/analysis/run_runtime_memory_scaling.py", "--no-write"],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling_report.py",
        ],
        ["scripts/analysis/report_runtime_memory_scaling.py", "--no-write"],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_runtime_memory_scaling_v1_1_report.py",
        ],
        ["scripts/analysis/report_runtime_memory_scaling_v1_1.py", "--no-write"],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/consensus",
            "-p",
            "test_query_support_optimization_design.py",
        ],
        [
            "scripts/analysis/report_query_support_optimization_design.py",
            "--json-in",
            ".agent/tmp/evaluator_bottleneck_diagnostic.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/consensus",
            "-p",
            "test_topology_query_support_fast_path.py",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/evaluation",
            "-p",
            "test_v2x_consensus_bridge_query_support_backend.py",
        ],
        [
            "scripts/analysis/profile_v2x_evaluator.py",
            "--node-counts",
            "500",
            "--force",
            "--query-support-backend",
            "both",
            "--diagnostics-mode",
            "full",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_node_count_10000_topk_backward_report.py",
        ],
        [
            "scripts/analysis/report_node_count_10000_topk_backward.py",
            "--json-in",
            ".agent/tmp/node_count_10000_topk_backward_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_gradient_step_size_diagnostic.py",
        ],
        [
            "scripts/analysis/run_gradient_step_size_diagnostic.py",
            "--node-count",
            "500",
            "--learning-rates",
            "1e-4,1e-3,1e-2",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_design.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_design.py",
            "--json-in",
            ".agent/tmp/score_head_only_teacher_update_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_support_smoothing_constructor.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_constructor.py",
            "--readiness-artifact",
            ".agent/tmp/support_smoothing_design.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_10k_smoke.py",
        ],
        [
            "scripts/analysis/run_support_smoothing_10k_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_loss_evaluator_sensitivity_review.py",
        ],
        [
            "scripts/analysis/report_loss_evaluator_sensitivity_review.py",
            "--json-in",
            ".agent/tmp/support_smoothing_10k_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_human_review_gate_package.py",
        ],
        [
            "scripts/analysis/report_human_review_gate_package.py",
            "--json-in",
            ".agent/tmp/loss_evaluator_sensitivity_review.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_support_smoothing_stabilization_design.py",
        ],
        [
            "scripts/analysis/report_support_smoothing_stabilization_design.py",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_directional_teacher_alignment_interpretation.py",
        ],
        [
            "scripts/analysis/report_directional_teacher_alignment.py",
            "--json-in",
            ".agent/tmp/directional_teacher_alignment_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_head_teacher_update_probe.py",
        ],
        [
            "scripts/analysis/run_score_head_only_teacher_update_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--alignment-modes",
            "sign_alignment",
            "--teacher-weights",
            "0.01,0.1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_delta_distillation_report.py",
        ],
        [
            "scripts/analysis/report_edge_score_delta_distillation.py",
            "--json-in",
            ".agent/tmp/edge_score_delta_distillation.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_loss_scale_probe.py",
        ],
        [
            "scripts/analysis/run_teacher_loss_scale_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--teacher-weights",
            "1,1e3",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_loss_scale_report.py",
        ],
        [
            "scripts/analysis/report_teacher_loss_scale_probe.py",
            "--json-in",
            ".agent/tmp/teacher_loss_scale_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_directional_teacher_alignment_probe.py",
        ],
        [
            "scripts/analysis/run_directional_teacher_alignment_probe.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--alignment-modes",
            "cosine_delta_alignment",
            "--teacher-weights",
            "0.1,1.0",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_teacher_report.py",
        ],
        [
            "scripts/analysis/report_edge_score_teacher_probe.py",
            "--json-in",
            ".agent/tmp/edge_score_teacher_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_teacher_guided_scorer_design.py",
        ],
        [
            "scripts/analysis/report_teacher_guided_scorer_design.py",
            "--json-in",
            ".agent/tmp/edge_score_teacher_interpretation.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_delta_distillation.py",
        ],
        [
            "scripts/analysis/run_edge_score_delta_distillation.py",
            "--node-count",
            "500",
            "--steps",
            "2",
            "--teacher-weights",
            "0.01,0.1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_gain_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_score_gain_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--compare-gains",
            "10,30",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_gain_tenk_report.py",
        ],
        [
            "scripts/analysis/report_score_gain_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/score_gain_tenk_few_step_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_combined_gain_temperature_probe.py",
        ],
        [
            "scripts/analysis/run_combined_gain_temperature_probe.py",
            "--node-count",
            "500",
            "--probe-steps",
            "2",
            "--score-output-gains",
            "10,30",
            "--temperatures",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_edge_score_teacher_probe.py",
        ],
        [
            "scripts/analysis/run_edge_score_teacher_probe.py",
            "--node-count",
            "500",
            "--teacher-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_all_mode_warm_start_report.py",
        ],
        [
            "scripts/analysis/report_all_mode_warm_start_10k.py",
            "--json-in",
            ".agent/tmp/all_mode_warm_start_10k_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_convergence_root_cause_audit.py",
        ],
        [
            "scripts/analysis/run_convergence_root_cause_audit.py",
            "--node-count",
            "500",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_scorer_parameterization_redesign.py",
        ],
        [
            "scripts/analysis/report_scorer_parameterization_redesign.py",
            "--json-in",
            ".agent/tmp/convergence_root_cause_audit.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_scorer_dynamic_range_diagnostic.py",
        ],
        [
            "scripts/analysis/run_scorer_dynamic_range_diagnostic.py",
            "--node-count",
            "500",
            "--score-scales",
            "1,10,30",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/models",
            "-p",
            "test_score_output_gain.py",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_output_gain_probe.py",
        ],
        [
            "scripts/analysis/run_score_output_gain_probe.py",
            "--node-count",
            "500",
            "--score-output-gains",
            "1,10,30",
            "--probe-steps",
            "1",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_longer_tenk_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_longer_tenk_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_longer_tenk_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_longer_tenk.py",
            "--json-in",
            ".agent/tmp/temperature_aware_longer_tenk_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_30step_tenk_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_30step_tenk_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_30step_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_30step_tenk.py",
            "--json-in",
            ".agent/tmp/temperature_aware_30step_tenk_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_all_mode_warm_start_10k_probe.py",
        ],
        [
            "scripts/analysis/run_all_mode_warm_start_10k_probe.py",
            "--node-count",
            "1000",
            "--max-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_tenk_report.py",
        ],
        [
            "scripts/analysis/report_temperature_aware_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/temperature_aware_tenk_few_step_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_temperature_aware_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_temperature_aware_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "30",
            "--row-softmax-temperature",
            "0.5",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_temperature_grid_probe.py",
        ],
        [
            "scripts/analysis/run_score_temperature_grid_probe.py",
            "--node-count",
            "500",
            "--score-scales",
            "3,10",
            "--temperatures",
            "1,2",
            "--probe-steps",
            "1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_row_softmax_temperature_design.py",
        ],
        [
            "scripts/analysis/report_row_softmax_temperature_design.py",
            "--json-in",
            ".agent/tmp/score_temperature_grid_probe.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_row_softmax_temperature_constructor.py",
        ],
        [
            "scripts/analysis/report_row_softmax_temperature_constructor.py",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_formal_temperature_grid_probe.py",
        ],
        [
            "scripts/analysis/run_formal_temperature_grid_probe.py",
            "--node-count",
            "500",
            "--score-scales",
            "3,10",
            "--temperatures",
            "1,0.5",
            "--probe-steps",
            "1",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scaled_tenk_report.py",
        ],
        [
            "scripts/analysis/report_score_scaled_tenk_few_step.py",
            "--json-in",
            ".agent/tmp/score_scaled_tenk_few_step_smoke.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scaled_tenk_few_step_smoke.py",
        ],
        [
            "scripts/analysis/run_score_scaled_tenk_few_step_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--score-scale",
            "3",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_score_scale_calibration.py",
        ],
        [
            "scripts/analysis/run_score_scale_calibration.py",
            "--node-count",
            "500",
            "--score-scales",
            "1,3,10",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_gradient_source_diagnostic.py",
        ],
        [
            "scripts/analysis/run_gradient_source_diagnostic.py",
            "--node-count",
            "500",
            "--loss-scales",
            "1,10",
            "--learning-rates",
            "1e-2,1e-1",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_loss_scale_calibrated_backward_smoke.py",
        ],
        [
            "scripts/analysis/run_loss_scale_calibrated_backward_smoke.py",
            "--node-count",
            "500",
            "--loss-scale",
            "1000",
            "--learning-rate",
            "1e-4",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_tenk_few_step_training_smoke.py",
        ],
        [
            "scripts/analysis/run_tenk_few_step_training_smoke.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_metric_flatness_diagnostic.py",
        ],
        [
            "scripts/analysis/run_metric_flatness_diagnostic.py",
            "--node-count",
            "500",
            "--max-steps",
            "2",
            "--perturb-edge-score-scales",
            "1e-5,1e-3",
            "--edge-score-only-steps",
            "2",
            "--learning-rate",
            "1e-4",
            "--loss-scale",
            "1000",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/training",
            "-p",
            "test_topk_support_sensitivity_probe.py",
        ],
        [
            "scripts/analysis/run_topk_support_sensitivity_probe.py",
            "--node-count",
            "500",
            "--perturb-scales",
            "1e-6,1e-4,1e-2",
            "--score-scales",
            "0.1,1,10",
            "--softmax-temperatures",
            "0.5,1,2",
            "--force",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_constructor_profile.py",
        ],
        ["scripts/analysis/profile_topology_constructor.py", "--node-counts", "100,500", "--no-write"],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_constructor_optimization_design.py",
        ],
        [
            "scripts/analysis/report_constructor_optimization_design.py",
            "--json-in",
            ".agent/tmp/constructor_bottleneck_diagnostic.json",
            "--no-write",
        ],
        [
            "-m",
            "unittest",
            "discover",
            "-s",
            "tests/topology",
            "-p",
            "test_topology_construction_fast_path.py",
        ],
        [
            "scripts/analysis/profile_topology_constructor.py",
            "--node-counts",
            "64",
            "--topk-backend",
            "both",
            "--force",
            "--no-write",
        ],
        ["-m", "unittest", "discover", "-s", "tests/scale"],
        ["scripts/analysis/run_scale_training_smoke.py", "--tier", "fast"],
        ["scripts/harness/verify_no_pbft_residue.py"],
        ["scripts/harness/verify_no_sampling_avalanche.py"],
        ["scripts/harness/verify_no_binomial_enumeration.py"],
        ["scripts/harness/verify_no_soft_hard_gap.py"],
        ["scripts/harness/verify_no_link_reliability_loss.py"],
        ["scripts/harness/verify_sparse_complexity.py"],
        ["scripts/harness/verify_model_contract.py"],
    ],
    "test": [
        ["-m", "unittest", "discover", "-s", "tests"],
    ],
}

COMMANDS["research-check"] = COMMANDS["source-check"]

# Lean default gate. Historical M/R diagnostic targets remain addressable by
# explicit name, but they are no longer part of `agent-check`.
COMMANDS["training-smoke-check"] = [
    [
        "-m",
        "unittest",
        "tests.training.test_training_smoke",
        "tests.training.test_intermediate_reliability_band_probe",
        "tests.training.test_de_ablation_bounds",
        "tests.training.test_production_training_verdict",
    ],
    ["scripts/analysis/run_training_smoke.py", "--config", "configs/training_smoke.yaml", "--smoke"],
]
COMMANDS["test"] = [
    [
        "-m",
        "unittest",
        "tests.training.test_training_smoke",
        "tests.training.test_intermediate_reliability_band_probe",
        "tests.training.test_de_ablation_bounds",
        "tests.training.test_production_training_verdict",
    ],
]
COMMANDS["intermediate-reliability-band-probe-check"] = [
    ["-m", "unittest", "tests.training.test_intermediate_reliability_band_probe"],
    ["scripts/analysis/run_intermediate_reliability_band_probe.py", "--node-count", "500"],
]
COMMANDS["standard-generalization"] = [
    [
        "scripts/analysis/run_standard_generalization.py",
        "--train-densities",
        "150,300,600",
        "--train-times",
        "0,4,8",
        "--test-densities",
        "100,450,800",
        "--test-times",
        "12,20",
        "--node-count",
        "2000",
        "--max-steps",
        "180",
        "--run-name",
        "standard_generalization_v1",
    ],
]
COMMANDS["generalization"] = COMMANDS["standard-generalization"]
COMMANDS["production-check"] = [
    [
        "scripts/analysis/run_production_training.py",
        "--node-counts",
        "2000,10000",
        "--max-steps",
        "30",
        "--focus-node-count",
        "10000",
    ],
]
COMMANDS["de-ablation"] = [
    [
        "scripts/analysis/run_de_ablation.py",
        "--node-count",
        "2000",
        "--max-steps",
        "120",
        "--seed",
        "42",
        "--reliability-target",
        "0.01",
        "--run-name",
        "de_ablation_v1",
    ],
]
COMMANDS["harness-check"] = (
    [
        ["scripts/harness/verify_model_contract.py"],
        ["scripts/harness/verify_no_pbft_residue.py"],
        ["scripts/harness/verify_no_sampling_avalanche.py"],
        ["scripts/harness/verify_no_binomial_enumeration.py"],
        ["scripts/harness/verify_no_link_reliability_loss.py"],
        ["scripts/harness/verify_no_soft_hard_gap.py"],
        ["scripts/harness/verify_sparse_complexity.py"],
    ]
    + COMMANDS["model-check"]
    + COMMANDS["topology-check"]
    + COMMANDS["loss-check"]
    + COMMANDS["training-smoke-check"]
    + COMMANDS["env-feasibility-check"]
    + COMMANDS["evaluation-check"]
    + COMMANDS["integration-check"]
    + [
        ["-m", "unittest", "tests.topology.test_straight_through_gradient"],
        ["-m", "unittest", "tests.loss.test_scale_invariant_backward"],
        ["-m", "unittest", "tests.models.test_scorer_dynamic_range_fix"],
        [
            "scripts/analysis/run_production_training.py",
            "--node-counts",
            "500",
            "--max-steps",
            "5",
            "--focus-node-count",
            "500",
            "--reliability-target",
            "0.05",
        ],
    ]
)
COMMANDS["agent-check"] = COMMANDS["harness-check"] + COMMANDS["source-check"] + COMMANDS["skill-check"]


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in COMMANDS:
        known = ", ".join(sorted(COMMANDS))
        print(f"Usage: make <target>. Known targets: {known}")
        raise SystemExit(2)

    target = sys.argv[1]
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    for args in COMMANDS[target]:
        completed = subprocess.run([sys.executable, "-B", *args], cwd=ROOT, env=env)
        if completed.returncode != 0:
            raise SystemExit(completed.returncode)


if __name__ == "__main__":
    main()
