"""Unified V2X-TOPO-GNN consensus mainline.

This package hosts the single, self-consistent mathematical mainline defined by
``docs/GLOBAL_CONSENSUS_MATH_REDESIGN.md``.  It deliberately does **not** reuse
the legacy ``src/consensus`` evaluators, which encode the forbidden mean-field /
iid-beta-tail closures (see ``docs/REFACTOR_PROGRESS.md`` decision log).

Modules are added gate by gate:

- ``symmetric_polynomials`` -- G2 / spec §4: exact weighted distinct-peer
  k-subset distribution via elementary symmetric polynomials, inclusion
  probabilities, and the shared ancestral sampler.
"""

from .global_evaluator import (
    BucketedPadding,
    DegreeBucket,
    GlobalConsensusResult,
    SourcePadding,
    build_bucketed_padding,
    build_source_padding,
    evaluate_global_consensus,
    monte_carlo_global_success,
    simulate_model_joint,
)
from .emission import (
    EmissionConfig,
    RecurrenceState,
    ScalarEmissionRecurrentModel,
    global_risk_contribution,
    hidden_state_boundedness_ablation,
    neg_log_S_r,
    recurrence_step,
    risk_emission,
)
from .finite_blocklength import (
    BlocklengthSpec,
    HeadlineLinkConfig,
    PathLoss3GPP,
    averaged_link_success,
    channel_capacity,
    channel_dispersion,
    fading_average_success,
    fbl_error,
    fbl_link_success,
    gaussian_q,
    harq_residual_error,
    mode2_collision_probability,
    payload_bits,
    poll_success,
    sinr_linear_from_geometry,
)
from .model import (
    FiLM,
    OperatingPointConfig,
    PreferenceConditionedTopologyGNN,
    augmented_chebyshev,
    directional_steering,
    model_operating_point,
    pareto_indices,
    sample_simplex,
    train_preference_model,
)
from .objectives import (
    attempt_energy,
    blocklength_head,
    completion_delay,
    delay_from_cdf_reference,
    expected_attempts,
    network_energy,
    power_head,
    wall_clock_attempts,
)
from .quorum_dp import (
    QuorumDecision,
    bruteforce_quorum_distribution,
    quorum_decision_probabilities,
    quorum_response_distribution,
)
from .topology import (
    CandidateGraph,
    LoadCoupledLinkConfig,
    aggregate_interference,
    build_candidate_graph,
    half_duplex_probability,
    link_sinr_with_interference,
    load_coupled_link_reliability,
    los_probability,
    mode2_collision_from_load,
    queueing_utilisation,
    receiver_load,
)
from .snowball import (
    build_transition,
    initial_distribution,
    readout_preference,
    snowball_layout,
    snowball_state_count,
    terminal_outcomes,
)
from .symmetric_polynomials import (
    SubsetPolicy,
    edge_inclusion_log_probability,
    edge_inclusion_probability,
    elementary_symmetric,
    enumerate_subset_distribution,
    log_elementary_symmetric,
    sample_k_subset,
    subset_log_probability,
    verify_sampler_matches_distribution,
)

__all__ = [
    "BlocklengthSpec",
    "BucketedPadding",
    "EmissionConfig",
    "RecurrenceState",
    "ScalarEmissionRecurrentModel",
    "global_risk_contribution",
    "hidden_state_boundedness_ablation",
    "neg_log_S_r",
    "recurrence_step",
    "risk_emission",
    "CandidateGraph",
    "DegreeBucket",
    "FiLM",
    "OperatingPointConfig",
    "PreferenceConditionedTopologyGNN",
    "augmented_chebyshev",
    "directional_steering",
    "model_operating_point",
    "pareto_indices",
    "sample_simplex",
    "train_preference_model",
    "LoadCoupledLinkConfig",
    "aggregate_interference",
    "attempt_energy",
    "blocklength_head",
    "build_candidate_graph",
    "completion_delay",
    "delay_from_cdf_reference",
    "expected_attempts",
    "half_duplex_probability",
    "network_energy",
    "power_head",
    "wall_clock_attempts",
    "link_sinr_with_interference",
    "load_coupled_link_reliability",
    "los_probability",
    "mode2_collision_from_load",
    "queueing_utilisation",
    "receiver_load",
    "GlobalConsensusResult",
    "HeadlineLinkConfig",
    "PathLoss3GPP",
    "QuorumDecision",
    "averaged_link_success",
    "channel_capacity",
    "channel_dispersion",
    "fading_average_success",
    "fbl_error",
    "fbl_link_success",
    "gaussian_q",
    "harq_residual_error",
    "mode2_collision_probability",
    "payload_bits",
    "poll_success",
    "sinr_linear_from_geometry",
    "SourcePadding",
    "SubsetPolicy",
    "build_bucketed_padding",
    "build_source_padding",
    "build_transition",
    "evaluate_global_consensus",
    "initial_distribution",
    "monte_carlo_global_success",
    "readout_preference",
    "simulate_model_joint",
    "snowball_layout",
    "snowball_state_count",
    "terminal_outcomes",
    "bruteforce_quorum_distribution",
    "edge_inclusion_log_probability",
    "edge_inclusion_probability",
    "elementary_symmetric",
    "enumerate_subset_distribution",
    "log_elementary_symmetric",
    "quorum_decision_probabilities",
    "quorum_response_distribution",
    "sample_k_subset",
    "subset_log_probability",
    "verify_sampler_matches_distribution",
]
